# Generated by Django 4.1.5 on 2023-01-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artem_and_point', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_order',
            name='_amount',
            field=models.IntegerField(db_column='amount', default=1),
        ),
    ]
